--- # this my my task copying section
- name: copying a file from ansible server to host servers
  hosts: webservers
  user: ansible
  connection: ssh
  become: true

  tasks:
    - name: copying a file from ansible server to hosts
      copy:

        src: /home/ansible/index.html

        dest: /home/ansible
